import Lake
open Lake DSL System

/-! Build config for the cleango library — Lean 4 bindings to libclingo,
fully auto-generated by lean-bindgen with thin wrapper modules. -/

structure CBinding where
  shimSources : Array FilePath
  includeDirs : Array FilePath := #[]
  cFlags      : Array String   := #[]

def buildShimObject {n}
    (pkg : NPackage n) (cfg : CBinding) (src : FilePath)
    : FetchM (Job FilePath) := do
  let oFile  := pkg.buildDir / src.withExtension "o"
  let srcJob ← inputTextFile (pkg.dir / src)
  let leanInc := (← getLeanIncludeDir).toString
  let userIncs := cfg.includeDirs.foldl
    (init := #[]) (fun acc d => acc ++ #["-I", (pkg.dir / d).toString])
  buildO oFile srcJob
    (weakArgs  := #["-I", leanInc] ++ userIncs)
    (traceArgs := #["-fPIC"] ++ cfg.cFlags)

def buildCBinding {n}
    (pkg : NPackage n) (libName : String) (cfg : CBinding)
    : FetchM (Job FilePath) := do
  let oJobs ← cfg.shimSources.mapM (buildShimObject pkg cfg)
  buildStaticLib (pkg.staticLibDir / nameToStaticLib libName) oJobs

-- Where Homebrew installs clingo on macOS arm64.
def clingoIncludeDir : FilePath := "/opt/homebrew/include"
def clingoLibDir     : FilePath := "/opt/homebrew/lib"

-- Use system clingo header for runtime. AST struct helpers won't compile
-- against system clingo 5.8+ (uses attribute-based AST API), so we suppress
-- those errors with a compat define.
def refIncludeDir : FilePath := "../../reference/cleango/bindings"

package «cleango» where
  moreLinkArgs := #[s!"-L{clingoLibDir}", "-lclingo"]

@[default_target]
lean_lib Clingo where

lean_exe «test_ffi» where
  root := `test.TestFFI

lean_exe «test_all» where
  root := `test.TestAll

extern_lib «clingo-shim» pkg :=
  buildCBinding pkg "clingo-shim" {
    shimSources := #[
      -- Entirely auto-generated by lean-bindgen.
      "csrc/clingo-bindings-shim.c"
    ]
    includeDirs := #[refIncludeDir, clingoIncludeDir]
    cFlags := #["-Wno-incompatible-pointer-types", "-Wno-pointer-sign"]
  }
