/* Auto-generated by lean-bindgen. Do not edit. */

#include "lean/lean.h"

#include <pthread.h>

#include <stdlib.h>

#include <string.h>

#include "zlib_lean_api.h"

static void noop_foreach(void *mod, b_lean_obj_arg fn) { (void)mod; (void)fn; }

static void finalize_deflate_state(void * ptr) {
  zlib_deflate_free((zlib_deflate_state *)ptr);
}

static lean_external_class * g_deflate_state_class = NULL;

static pthread_once_t g_deflate_state_once = PTHREAD_ONCE_INIT;

static void init_deflate_state_class(void) {
  g_deflate_state_class = lean_register_external_class(&finalize_deflate_state, &noop_foreach);
}

lean_external_class * get_deflate_state_class(void) {
  pthread_once(&g_deflate_state_once, init_deflate_state_class);
  return g_deflate_state_class;
}

static void finalize_inflate_state(void * ptr) {
  zlib_inflate_free((zlib_inflate_state *)ptr);
}

static lean_external_class * g_inflate_state_class = NULL;

static pthread_once_t g_inflate_state_once = PTHREAD_ONCE_INIT;

static void init_inflate_state_class(void) {
  g_inflate_state_class = lean_register_external_class(&finalize_inflate_state, &noop_foreach);
}

lean_external_class * get_inflate_state_class(void) {
  pthread_once(&g_inflate_state_once, init_inflate_state_class);
  return g_inflate_state_class;
}

LEAN_EXPORT uint32_t lean_zlib_crc32(uint32_t init, b_lean_obj_arg data) {
  uint8_t const *data_ptr = lean_sarray_cptr(data);
  size_t data_len = lean_sarray_size(data);
  return (uint32_t)(zlib_crc32(init, data_ptr, data_len));
}

LEAN_EXPORT uint32_t lean_zlib_adler32(uint32_t init, b_lean_obj_arg data) {
  uint8_t const *data_ptr = lean_sarray_cptr(data);
  size_t data_len = lean_sarray_size(data);
  return (uint32_t)(zlib_adler32(init, data_ptr, data_len));
}

LEAN_EXPORT lean_obj_res lean_zlib_compress(b_lean_obj_arg src, uint8_t level) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  uint8_t const *src_ptr = lean_sarray_cptr(src);
  size_t src_len = lean_sarray_size(src);
  if (zlib_compress(src_ptr, src_len, level, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_gzip_compress(b_lean_obj_arg src, uint8_t level) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  uint8_t const *src_ptr = lean_sarray_cptr(src);
  size_t src_len = lean_sarray_size(src);
  if (gzip_compress(src_ptr, src_len, level, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_raw_deflate_compress(b_lean_obj_arg src, uint8_t level) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  uint8_t const *src_ptr = lean_sarray_cptr(src);
  size_t src_len = lean_sarray_size(src);
  if (raw_deflate_compress(src_ptr, src_len, level, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_zlib_decompress(b_lean_obj_arg src) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  uint8_t const *src_ptr = lean_sarray_cptr(src);
  size_t src_len = lean_sarray_size(src);
  if (zlib_decompress(src_ptr, src_len, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_gzip_decompress(b_lean_obj_arg src) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  uint8_t const *src_ptr = lean_sarray_cptr(src);
  size_t src_len = lean_sarray_size(src);
  if (gzip_decompress(src_ptr, src_len, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_raw_deflate_decompress(b_lean_obj_arg src) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  uint8_t const *src_ptr = lean_sarray_cptr(src);
  size_t src_len = lean_sarray_size(src);
  if (raw_deflate_decompress(src_ptr, src_len, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_gzip_deflate_new(uint8_t level) {
  zlib_deflate_state * out = NULL;
  if (gzip_deflate_new(level, &out)) {
      lean_object* val = lean_alloc_external(get_deflate_state_class(), (void *)out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, val);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_gzip_deflate_push(b_lean_obj_arg state, b_lean_obj_arg chunk) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  zlib_deflate_state * state_c = (zlib_deflate_state *) lean_get_external_data(state);
  uint8_t const *chunk_ptr = lean_sarray_cptr(chunk);
  size_t chunk_len = lean_sarray_size(chunk);
  if (gzip_deflate_push(state_c, chunk_ptr, chunk_len, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_gzip_deflate_finish(b_lean_obj_arg state) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  zlib_deflate_state * state_c = (zlib_deflate_state *) lean_get_external_data(state);
  if (gzip_deflate_finish(state_c, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_gzip_inflate_new() {
  zlib_inflate_state * out = NULL;
  if (gzip_inflate_new(&out)) {
      lean_object* val = lean_alloc_external(get_inflate_state_class(), (void *)out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, val);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_gzip_inflate_push(b_lean_obj_arg state, b_lean_obj_arg chunk) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  zlib_inflate_state * state_c = (zlib_inflate_state *) lean_get_external_data(state);
  uint8_t const *chunk_ptr = lean_sarray_cptr(chunk);
  size_t chunk_len = lean_sarray_size(chunk);
  if (gzip_inflate_push(state_c, chunk_ptr, chunk_len, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_gzip_inflate_finish(b_lean_obj_arg state) {
  uint8_t *out = NULL;
  size_t out_len = 0;
  zlib_inflate_state * state_c = (zlib_inflate_state *) lean_get_external_data(state);
  if (gzip_inflate_finish(state_c, &out, &out_len)) {
      lean_object* ba = lean_alloc_sarray(1, out_len, out_len);
      memcpy(lean_sarray_cptr(ba), out, out_len);
      free(out);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, ba);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = zlib_last_error();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_zlib_last_error() {
  char const *_ret = zlib_last_error();
  if (_ret == NULL) return lean_io_result_mk_ok(lean_box(0));
  lean_object* some = lean_alloc_ctor(1, 1, 0);
  lean_ctor_set(some, 0, lean_mk_string(_ret));
  return lean_io_result_mk_ok(some);
}
