/* Auto-generated by lean-bindgen. Do not edit. */

#include "lean/lean.h"

#include <pthread.h>

#include "counter.h"

static void noop_foreach(void *mod, b_lean_obj_arg fn) { (void)mod; (void)fn; }

static counter_error_t lean_to_error(uint8_t cidx) {
  switch (cidx) {
    case 0:
      return counter_error_none;
    case 1:
      return counter_error_overflow;
    case 2:
      return counter_error_null_pointer;
    default:
      return (counter_error_t)0;
  }
}

static uint8_t error_to_lean(counter_error_t v) {
  switch (v) {
    case counter_error_none:
      return 0;
    case counter_error_overflow:
      return 1;
    case counter_error_null_pointer:
      return 2;
    default:
      return 0;
  }
}

static void finalize_counter(void * ptr) {
  counter_free((counter_t *)ptr);
}

static lean_external_class * g_counter_class = NULL;

static pthread_once_t g_counter_once = PTHREAD_ONCE_INIT;

static void init_counter_class(void) {
  g_counter_class = lean_register_external_class(&finalize_counter, &noop_foreach);
}

lean_external_class * get_counter_class(void) {
  pthread_once(&g_counter_once, init_counter_class);
  return g_counter_class;
}

LEAN_EXPORT lean_obj_res lean_counter_create(int32_t initial_value) {
  return lean_io_result_mk_ok(lean_alloc_external(get_counter_class(), (void *)(counter_create(initial_value))));
}

LEAN_EXPORT lean_obj_res lean_counter_increment(b_lean_obj_arg c, int32_t amount) {
  counter_t * c_c = (counter_t *) lean_get_external_data(c);
  if (counter_increment(c_c, amount)) {
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, lean_box(0));
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = counter_error_message();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_counter_get_value(b_lean_obj_arg c) {
  counter_t * c_c = (counter_t *) lean_get_external_data(c);
  return lean_io_result_mk_ok(lean_box_uint32(counter_get_value(c_c)));
}

LEAN_EXPORT lean_obj_res lean_counter_version(lean_obj_arg _unit) {
  int32_t major;
  int32_t minor;
  int32_t patch;
  counter_version(&major, &minor, &patch);
  lean_object* _p2 = lean_box_uint32(patch);
  lean_object* _t1 = lean_alloc_ctor(0, 2, 0);
  lean_ctor_set(_t1, 0, lean_box_uint32(minor));
  lean_ctor_set(_t1, 1, _p2);
  lean_object* _p1 = _t1;
  lean_object* _result = lean_alloc_ctor(0, 2, 0);
  lean_ctor_set(_result, 0, lean_box_uint32(major));
  lean_ctor_set(_result, 1, _p1);
  return _result;
}
