/* Auto-generated by lean-bindgen. Do not edit. */

#include "lean/lean.h"

#include <pthread.h>

#include <stdlib.h>

#include <string.h>

#include "clingo.h"

static void noop_foreach(void *mod, b_lean_obj_arg fn) { (void)mod; (void)fn; }

/* Forward declarations for recursive helpers. */

static void free_location(clingo_location_t *p);

lean_object* location_to_lean(clingo_location_t v);

clingo_location_t lean_to_location(b_lean_obj_arg obj);

static clingo_error_t lean_to_error(uint8_t cidx) {
  switch (cidx) {
    case 0:
      return clingo_error_success;
    case 1:
      return clingo_error_runtime;
    case 2:
      return clingo_error_logic;
    case 3:
      return clingo_error_bad_alloc;
    case 4:
      return clingo_error_unknown;
    default:
      return (clingo_error_t)0;
  }
}

static uint8_t error_to_lean(clingo_error_t v) {
  switch (v) {
    case clingo_error_success:
      return 0;
    case clingo_error_runtime:
      return 1;
    case clingo_error_logic:
      return 2;
    case clingo_error_bad_alloc:
      return 3;
    case clingo_error_unknown:
      return 4;
    default:
      return 0;
  }
}

static clingo_warning_t lean_to_warning(uint8_t cidx) {
  switch (cidx) {
    case 0:
      return clingo_warning_operation_undefined;
    case 1:
      return clingo_warning_runtime_error;
    case 2:
      return clingo_warning_atom_undefined;
    case 3:
      return clingo_warning_file_included;
    case 4:
      return clingo_warning_variable_unbounded;
    case 5:
      return clingo_warning_global_variable;
    case 6:
      return clingo_warning_other;
    default:
      return (clingo_warning_t)0;
  }
}

static uint8_t warning_to_lean(clingo_warning_t v) {
  switch (v) {
    case clingo_warning_operation_undefined:
      return 0;
    case clingo_warning_runtime_error:
      return 1;
    case clingo_warning_atom_undefined:
      return 2;
    case clingo_warning_file_included:
      return 3;
    case clingo_warning_variable_unbounded:
      return 4;
    case clingo_warning_global_variable:
      return 5;
    case clingo_warning_other:
      return 6;
    default:
      return 0;
  }
}

static void finalize_control(void * ptr) {
  clingo_control_free((clingo_control_t *)ptr);
}

static lean_external_class * g_control_class = NULL;

static pthread_once_t g_control_once = PTHREAD_ONCE_INIT;

static void init_control_class(void) {
  g_control_class = lean_register_external_class(&finalize_control, &noop_foreach);
}

lean_external_class * get_control_class(void) {
  pthread_once(&g_control_once, init_control_class);
  return g_control_class;
}

static void free_location(clingo_location_t * p) {
  if (p->begin_file) {
    free((void *)p->begin_file);
  }
  if (p->end_file) {
    free((void *)p->end_file);
  }
}

lean_object* location_to_lean(clingo_location_t v) {
  lean_object* o = lean_alloc_ctor(0, 2, 32);
  lean_ctor_set(o, 0, lean_mk_string(v.begin_file == NULL ? "" : v.begin_file));
  lean_ctor_set(o, 1, lean_mk_string(v.end_file == NULL ? "" : v.end_file));
  lean_ctor_set_usize(o, 2, (size_t)v.begin_line);
  lean_ctor_set_usize(o, 3, (size_t)v.end_line);
  lean_ctor_set_usize(o, 4, (size_t)v.begin_column);
  lean_ctor_set_usize(o, 5, (size_t)v.end_column);
  return o;
}

clingo_location_t lean_to_location(b_lean_obj_arg obj) {
  clingo_location_t v;
  v.begin_file = strdup(lean_string_cstr(lean_ctor_get(obj, 0)));
  v.end_file = strdup(lean_string_cstr(lean_ctor_get(obj, 1)));
  v.begin_line = (size_t)lean_ctor_get_usize(obj, 2);
  v.end_line = (size_t)lean_ctor_get_usize(obj, 3);
  v.begin_column = (size_t)lean_ctor_get_usize(obj, 4);
  v.end_column = (size_t)lean_ctor_get_usize(obj, 5);
  return v;
}

void clingo_logger_t_trampoline(clingo_warning_t code, char const *message, void *data) {
  lean_object* closure = (lean_object*)data;
  lean_object* _lean_0 = lean_box(warning_to_lean(code));
  lean_object* _lean_1 = lean_mk_string(message == NULL ? "" : message);
  lean_inc(closure);
  lean_object* _result = lean_apply_3(closure, _lean_0, _lean_1, lean_io_mk_world());
  lean_dec(_result);
}

LEAN_EXPORT lean_obj_res lean_clingo_signature_create(b_lean_obj_arg name, uint32_t arity, uint8_t positive) {
  uint64_t signature;
  char const *name_c = lean_string_cstr(name);
  if (clingo_signature_create(name_c, arity, positive, &signature)) {
      lean_object* val = lean_box_uint64((uint64_t)signature);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, val);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = clingo_error_message();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_clingo_signature_name(uint64_t signature) {
  char const *_ret = clingo_signature_name(signature);
  return lean_mk_string(_ret == NULL ? "" : _ret);
}

LEAN_EXPORT uint32_t lean_clingo_signature_arity(uint64_t signature) {
  return (uint32_t)(clingo_signature_arity(signature));
}

LEAN_EXPORT uint8_t lean_clingo_signature_is_positive(uint64_t signature) {
  return clingo_signature_is_positive(signature) ? 1 : 0;
}

LEAN_EXPORT uint8_t lean_clingo_signature_is_negative(uint64_t signature) {
  return clingo_signature_is_negative(signature) ? 1 : 0;
}

LEAN_EXPORT uint8_t lean_clingo_signature_is_equal_to(uint64_t a, uint64_t b) {
  return clingo_signature_is_equal_to(a, b) ? 1 : 0;
}

LEAN_EXPORT uint8_t lean_clingo_signature_is_less_than(uint64_t a, uint64_t b) {
  return clingo_signature_is_less_than(a, b) ? 1 : 0;
}

LEAN_EXPORT size_t lean_clingo_signature_hash(uint64_t signature) {
  return (size_t)(clingo_signature_hash(signature));
}

LEAN_EXPORT lean_obj_res lean_clingo_error_code() {
  return lean_io_result_mk_ok(lean_box(error_to_lean(clingo_error_code())));
}

LEAN_EXPORT lean_obj_res lean_clingo_error_string(uint8_t code) {
  clingo_error_t code_c = lean_to_error(code);
  char const *_ret = clingo_error_string(code_c);
  return lean_mk_string(_ret == NULL ? "" : _ret);
}

LEAN_EXPORT lean_obj_res lean_clingo_control_interrupt(b_lean_obj_arg control) {
  clingo_control_t * control_c = (clingo_control_t *) lean_get_external_data(control);
  clingo_control_interrupt(control_c);
  return lean_io_result_mk_ok(lean_box(0));
}

LEAN_EXPORT lean_obj_res lean_clingo_parse_term(b_lean_obj_arg string, b_lean_obj_arg logger, uint32_t message_limit) {
  uint64_t symbol;
  char const *string_c = lean_string_cstr(string);
  lean_inc(logger);
  if (clingo_parse_term(string_c, clingo_logger_t_trampoline, (void*)logger, message_limit, &symbol)) {
        lean_dec(logger);
      lean_object* val = lean_box_uint64((uint64_t)symbol);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, val);
      return lean_io_result_mk_ok(ok);
    } else {
        lean_dec(logger);
      char const *msg = clingo_error_message();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_clingo_symbol_create_function(b_lean_obj_arg name, b_lean_obj_arg arguments, uint8_t positive) {
  uint64_t symbol;
  char const *name_c = lean_string_cstr(name);
  lean_array_object *arguments_arr_obj = lean_to_array(arguments);
  size_t arguments_size = arguments_arr_obj->m_size;
  if (arguments_size > SIZE_MAX / sizeof(uint64_t)) lean_internal_panic("lean-bindgen: array size overflow");
  uint64_t *arguments_buf = (uint64_t *)malloc(sizeof(uint64_t) * (arguments_size > 0 ? arguments_size : 1));
  for (size_t _arr_i = 0; _arr_i < arguments_size; _arr_i++) {
    lean_array_object *_arr_obj = arguments_arr_obj;
    arguments_buf[_arr_i] = (uint64_t)lean_unbox_uint64(_arr_obj->m_data[_arr_i]);
  }
  if (clingo_symbol_create_function(name_c, arguments_buf, arguments_size, positive, &symbol)) {
        free(arguments_buf);
      lean_object* val = lean_box_uint64((uint64_t)symbol);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, val);
      return lean_io_result_mk_ok(ok);
    } else {
        free(arguments_buf);
      char const *msg = clingo_error_message();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}
