// Auto-generated by lean-bindgen. Do not edit.
#include "lean/lean.h"
#include "clingo.h"

LEAN_EXPORT lean_obj_res lean_clingo_signature_create(b_lean_obj_arg name, uint32_t arity, uint8_t positive) {
  clingo_signature_t signature;
  char const *name_c = lean_string_cstr(name);
  if (clingo_signature_create(name_c, arity, positive, &signature)) {
      lean_object* val = lean_box_uint64((uint64_t)signature);
      lean_object* ok = lean_alloc_ctor(1, 1, 0);
      lean_ctor_set(ok, 0, val);
      return lean_io_result_mk_ok(ok);
    } else {
      char const *msg = clingo_error_message();
      if (msg == NULL) msg = "";
      lean_object* err = lean_alloc_ctor(0, 1, 0);
      lean_ctor_set(err, 0, lean_mk_string(msg));
      return lean_io_result_mk_ok(err);
    }
}

LEAN_EXPORT lean_obj_res lean_clingo_signature_name(uint64_t signature) {
  char const *_ret = clingo_signature_name(signature);
  return lean_mk_string(_ret == NULL ? "" : _ret);
}

LEAN_EXPORT uint32_t lean_clingo_signature_arity(uint64_t signature) {
  return (uint32_t)(clingo_signature_arity(signature));
}

LEAN_EXPORT uint8_t lean_clingo_signature_is_positive(uint64_t signature) {
  return clingo_signature_is_positive(signature) ? 1 : 0;
}

LEAN_EXPORT uint8_t lean_clingo_signature_is_negative(uint64_t signature) {
  return clingo_signature_is_negative(signature) ? 1 : 0;
}

LEAN_EXPORT uint8_t lean_clingo_signature_is_equal_to(uint64_t a, uint64_t b) {
  return clingo_signature_is_equal_to(a, b) ? 1 : 0;
}

LEAN_EXPORT uint8_t lean_clingo_signature_is_less_than(uint64_t a, uint64_t b) {
  return clingo_signature_is_less_than(a, b) ? 1 : 0;
}

LEAN_EXPORT size_t lean_clingo_signature_hash(uint64_t signature) {
  return (size_t)(clingo_signature_hash(signature));
}
